const CACHE = 'black-moon-demo-v30';
const ASSETS = ['./','./index.html','./styles.css','./game.js','./manifest.webmanifest','./assets/icon.svg','./assets/main-menu/main-menu-v3.png','./assets/references/character-select.png','./assets/battle/backgrounds/candlelit_ritual_table.png','./assets/characters/portraits/player_blackcat.png','./assets/characters/portraits/ironfang_bulldog.png','./assets/characters/portraits/foxtail_fox.png','./assets/characters/portraits/rabbit_noble.png','./assets/characters/portraits/owl_gentleman.png','./assets/characters/animation-sheets/player_blackcat_sheet.png','./assets/characters/animation-sheets/ironfang_bulldog_sheet.png','./assets/characters/animation-sheets/foxtail_fox_sheet.png','./assets/characters/animation-sheets/rabbit_noble_sheet.png','./assets/characters/animation-sheets/owl_gentleman_sheet.png','./assets/effects/fireflies_and_gold_particles_sheet.png','./assets/battle/cards-and-items/cards_items_sheet_01.png','./assets/battle/cards-and-items/icons_sheet_01.png','./assets/menu-buttons/button-start-game.png','./assets/menu-buttons/button-start-game-1.png','./assets/menu-buttons/button-tutorial.png','./assets/menu-buttons/button-tutorial-1.png','./assets/menu-buttons/button-story-mode.png','./assets/menu-buttons/button-story-mode-1.png','./assets/menu-buttons/button-black-moon-trial.png','./assets/menu-buttons/button-black-moon-trial-1.png','./assets/menu-buttons/button-pet-gallery.png','./assets/menu-buttons/button-pet-gallery-1.png','./assets/menu-buttons/button-settings.png','./assets/menu-buttons/button-settings-1.png'];
self.addEventListener('install', event => event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting())));
self.addEventListener('activate', event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim())));
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  event.respondWith(caches.match(event.request).then(hit => hit || fetch(event.request).then(response => {
    if (response.ok && new URL(event.request.url).origin === location.origin) caches.open(CACHE).then(cache => cache.put(event.request, response.clone()));
    return response;
  }).catch(() => caches.match('./index.html'))));
});
