const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
class Element{constructor(){this.classList={add(){},remove(){},toggle(){}};this.style={setProperty(){}};this.children=[];this.dataset={};this.open=false;this.textContent='';}append(...x){this.children.push(...x)}appendChild(x){this.children.push(x);return x}prepend(x){this.children.unshift(x)}querySelector(){return new Element}querySelectorAll(){return []}setAttribute(){}removeAttribute(){}addEventListener(){}showModal(){this.open=true}close(){this.open=false}remove(){}getBoundingClientRect(){return {left:10,top:10,width:50,height:70}}}
const nodes=new Map();const document={getElementById:id=>{if(!nodes.has(id))nodes.set(id,new Element);return nodes.get(id)},createElement:()=>new Element,body:new Element};
const context={document,localStorage:{getItem(){return null},setItem(){}},navigator:{},location:{protocol:'file:'},window:{addEventListener(){}},setTimeout:()=>0,clearTimeout(){},requestAnimationFrame:fn=>fn(),Math,console};context.window={...context.window,...context};vm.createContext(context);vm.runInContext(fs.readFileSync('game.js','utf8'),context);
const api=context.window.__BLACK_MOON__;assert(api,'缺少调试 API');assert.equal(api.PLAYERS.length,4);assert.deepEqual(Array.from(api.PLAYERS,x=>x.id),['shadow','fang','tail','snow'],'四个核心角色不正确');assert(api.PLAYERS.every(x=>x.art),'核心角色缺少正式立绘');assert.equal(api.CARDS.length,6);assert(api.CARDS.every(card=>card.rarity&&card.effect),'卡牌缺少稀有度或效果');assert.equal(api.AI.length,6);assert(api.PLAYERS.every(player=>player.tags.length===3&&player.quote),'角色性格资料不完整');assert(api.claimTrue([{id:'wild',wild:true},{id:'bone'}],'bone'));assert(api.freshState().rivals.every(rival=>rival.portrait),'可见对手不应回退为 emoji 占位');
api.endIntro();assert.equal(typeof nodes.get('storyModeBtn').onclick,'function','剧情模式按钮不可点击');assert.equal(typeof nodes.get('trialBtn').onclick,'function','黑月试炼按钮不可点击');nodes.get('startBtn').onclick();assert.equal(nodes.get('characterGrid').children.length,4,'角色选择未渲染');nodes.get('confirmCharacterBtn').onclick();assert(nodes.get('hand').children.length>=5,'开局未发牌');assert.match(nodes.get('storyText').textContent,/旧钟街/,'开局剧情未显示');nodes.get('nextStoryBtn').onclick();assert.match(nodes.get('storyText').textContent,/三位对手/,'剧情推进失败');nodes.get('hand').children[0].onclick();nodes.get('skipMotionBtn').onclick();assert.match(nodes.get('motionLog').textContent,/快速结算/);
const html=fs.readFileSync('index.html','utf8');assert(html.includes('assets/main-menu-v2.png'),'主菜单未使用新背景路径');assert(/<section[^>]+id="menuScreen"[\s\S]*?<img class="menu-art" src="assets\/main-menu-v2\.png"/.test(html),'主菜单未直接渲染完整图片');assert(!/class="(?:menu-content|menu-cast|menu-scene)/.test(html),'主菜单仍包含旧视觉层');assert(html.includes('assets/battle/battle-screen.png'),'战斗界面未使用新背景路径');assert(fs.readFileSync('game.js','utf8').includes("portrait:'assets/portraits/owl-chief.png'"),'剧情猫头鹰未使用新立绘');for(const scene of ['main-menu-v2.png','character-select.png','battle-screen.png','tavern-style.png'])assert(new RegExp(`<img[^>]+${scene.replace('.', '\\.')}[^>]*>`).test(html),`参考图未接入实际 DOM：${scene}`);const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'HTML 存在重复 ID');
for(const asset of ['assets/main-menu-v2.png','assets/battle/battle-screen.png','assets/portraits/owl-chief.png','assets/portraits/full/shadow.png','assets/portraits/full/fang.png','assets/portraits/full/tail.png','assets/portraits/full/snow.png','assets/icon.svg','assets/intro/opening.mp4','assets/portraits/black-cat.svg','assets/portraits/crow.svg','assets/portraits/fox.svg','assets/portraits/rabbit.svg'])assert(fs.existsSync(asset),`缺少 ${asset}`);
console.log('完整流程冒烟通过：开场跳过 → 主菜单 → 角色选择 → 发牌 → 动画跳过');
